import { CohereClient } from 'cohere-ai';
import { prompts, PromptCategory } from '../config/prompts.config';
import { selectPromptCategory } from '../utils/promptSelector';

// Initialize Cohere Client with API Key
if (!process.env.COHERE_API_KEY) {
  throw new Error('Missing COHERE_API_KEY in environment variables');
}

const co = new CohereClient({
  token: process.env.COHERE_API_KEY,
});

export const cohereChat = async (userMessage: string): Promise<string> => {
  try {
    // Dynamically select prompt based on the user message
    const topic: PromptCategory = selectPromptCategory(userMessage);
    const promptText = `${prompts[topic]}\nUser: ${userMessage}\nAI:`;

    // Generate response using Cohere's SDK
    const response = await co.generate({
      model: 'command',
      prompt: promptText,
      maxTokens: 300,
      temperature: 0.7,
    });

    // Validate and extract the generation
    const reply = response.generations?.[0]?.text?.trim();
    if (!reply) {
      throw new Error('No response generated by Cohere AI');
    }

    return reply;
  } catch (error: any) {
    console.error('❌ Cohere API Error:', error.message || error);
    throw new Error('Cohere failed to generate a response');
  }
};
